version: '3'
services:
  haproxy:
    build:
      context: .
      dockerfile: haproxy.Dockerfile
    ports:
      - "80:80"
  pihole:
    build:
      context: .
      dockerfile: pihole.Dockerfile
    ports:
      - "53:53"
      - "53:53/udp"
      - "67:67/udp"
      - "8053:80"
    environment:
      ServerIP: 192.168.1.2
      DNS1: "127.0.0.1#54"
      DNS2: "127.0.0.1#54"
      TAINER_HOME: /volume1/docker/pihole
    volumes:
      - "/volume1/docker/pihole/etc/pihole:/etc/pihole"
      - "/volume1/docker/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
  crashplan:
    image: jlesage/crashplan-pro
    environment:
      USER_ID: 1024
      CRASHPLAN_SRV_MAX_MEM: 2048M
    volumes:
      - "/volume1/docker/crashplan/config:/config:rw"
      - "/volume1/docker/crashplan/storage:/storage:ro"
      - "/volume1:/volume1:ro"
    ports:
      - "5800:5800"
